---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: course
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: course
  template:
    metadata:
      labels:
        app: course
    spec:
      containers:
      - image: km20/course:1.0
        imagePullPolicy: Always
        name: course
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: course
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: course
